name: mirror-to-huggingface

on:
  push:
    branches: [ main ]
    paths:
      - 'Archive_2025_Bilingual_Edition_v1.1.pdf'
      - 'Cover.png'
      - 'index.html'
      - 'style.css'
      - 'README.md'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub==0.25.*

      - name: Mirror to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_ID: PhenoX-Chappy/Archive-2025
        run: |
          python tools/hf_upload.py             --repo_id "$HF_SPACE_ID"             --src_files "Archive_2025_Bilingual_Edition_v1.1.pdf,Cover.png,index.html,style.css,README.md"