name: archive-release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Archive 2025 ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            Archive_2025_Bilingual_Edition_v1.1.pdf
            Cover.png
            index.html
            style.css